export const countryAbbreviations = {
  portugal: 'PT',
  'united states': 'US',
  usa: 'US',
  germany: 'DE',
  deutschland: 'DE',
  china: 'CN',
  spain: 'ES',
  españa: 'ES',
  brazil: 'BR',
  brasil: 'BR',
  australia: 'AU',
  canada: 'CA',
  'south korea': 'KR',
  korea: 'KR',
  uae: 'AE',
  'united arab emirates': 'AE',
  dubai: 'AE',
  russia: 'RU',
  rusia: 'RU',
  argentina: 'AR',
  japan: 'JP',
  'south africa': 'ZA',
  'republic of south africa': 'ZA',
  italy: 'IT',
  france: 'FR',
  'united kingdom': 'GB',
  ireland: 'IE',
  netherlands: 'NL',
  belgium: 'BE',
  switzerland: 'CH',
  austria: 'AT',
  'czech republic': 'CZ',
  poland: 'PL',
  chile: 'CL',
  hungary: 'HU',
  serbia: 'RS',
  greece: 'GR',
  bulgaria: 'BG',
  romania: 'RO',
  ukraine: 'UA',
  belarus: 'BY',
  lithuania: 'LT',
  latvia: 'LV',
  estonia: 'EE',
  sweden: 'SE',
  norway: 'NO',
  finland: 'FI',
  denmark: 'DK',
  iceland: 'IS',
  mexico: 'MX',
  'costa rica': 'CR',
  colombia: 'CO',
  ecuador: 'EC',
  peru: 'PE',
  kenya: 'KE',
  ghana: 'GH',
  nigeria: 'NG',
  egypt: 'EG',
  turkey: 'TR',
  india: 'IN'
}

export const getCountryCode = (country) => {
  const normalizedCountry = country.trim().toLowerCase()
  return countryAbbreviations[normalizedCountry] || country
}
